# Generated by Django 6.0.4 on 2026-05-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mebel/')),
                ('category', models.CharField(choices=[('Д', 'Диваны'), ('КХ', 'Кухонные гарнитуры'), ('Ш', 'Шкафы'), ('КР', 'Кровати'), ('С', 'Столы')], max_length=2)),
                ('availability', models.CharField(choices=[('Е', 'Есть'), ('Н', 'Нет')], max_length=1)),
            ],
        ),
    ]
