# Generated by Django 6.0.4 on 2026-05-19 16:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_mebel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
